# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  - push
  - pull_request

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_joinfacesBuildCachePassword: ${{ secrets.BUILD_CACHE_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.0

      - name: Print tool versions
        run: |
          java -version
          ./gradlew --version
      - run: ./gradlew assemble -s
      - run: ./gradlew check -s
