# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Docs

on:
  push:
    branches-ignore:
      - 'dependabot**'

jobs:
  deploy-plugin:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_joinfacesDocsUser: ${{ secrets.JOINFACES_DOCS_USER }}
      ORG_GRADLE_PROJECT_joinfacesDocsPass: ${{ secrets.JOINFACES_DOCS_PASS }}
      ORG_GRADLE_PROJECT_joinfacesBuildCachePassword: ${{ secrets.BUILD_CACHE_PASSWORD }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
      - run: ./gradlew uploadDocumentation -s
